---
title: "SAMOS Day 5"
author: "AJ Smit"
editor: source
format: html
---

## Making maps in **ggplot2**

```{r}
# Load libraries
library(tidyverse)
library(ggpubr)

# Load data
load("data/SAMOS/other_data/south_africa_coast.Rdata")
load("data/SAMOS/other_data/sa_provinces.RData")
load("data/SAMOS/other_data/rast_annual.Rdata")
load("data/SAMOS/other_data/MUR.Rdata")
load("data/SAMOS/other_data/MUR_low_res.RData")

# Choose which SST product you would like to use
# sst <- MUR_low_res |> ungroup()
# OR
sst <- MUR

# The colour palette we will use for ocean temperature
cols11 <- c("#004dcd", "#0068db", "#007ddb", "#008dcf", "#009bbc",
            "#00a7a9", "#1bb298", "#6cba8f", "#9ac290", "#bec99a")
```

```{r}
ggplot(data = ChickWeight, aes(x = Time, y = weight)) +
  geom_point()
```

```{r}
ggplot(data = south_africa_coast, aes(x = lon, y = lat)) +
  geom_point() +
  geom_path()
```

```{r}
ggplot(data = south_africa_coast, aes(x = lon, y = lat)) +
  geom_polygon(colour = "red", fill = "grey70",
               aes(group = group)) # The land mask
```

```{r}
ggplot(data = south_africa_coast, aes(x = lon, y = lat)) +
  geom_polygon(colour = "red", fill = "grey70", aes(group = group)) +
  geom_path(data = sa_provinces, aes(group = group)) # The province borders
```

```{r}
ggplot(data = south_africa_coast, aes(x = lon, y = lat)) +
  geom_polygon(colour = "red", fill = "grey70", aes(group = group)) +
  geom_path(data = sa_provinces, aes(group = group)) + 
  coord_equal(xlim = c(15, 34), ylim = c(-36, -26), expand = 0) # Force lon/lat extent
```

```{r}
ggplot(data = south_africa_coast, aes(x = lon, y = lat)) +
  geom_tile(data = sst, aes(fill = bins)) + # The ocean temperatures
  geom_polygon(colour = "red", fill = "grey70", aes(group = group)) +
  geom_path(data = sa_provinces, aes(group = group)) +
  coord_equal(xlim = c(15, 34), ylim = c(-36, -26), expand = 0)
```

```{r}
ggplot(data = south_africa_coast, aes(x = lon, y = lat)) +
  geom_raster(data = sst, aes(fill = bins)) +
  geom_polygon(colour = "black", fill = "grey70",
               aes(group = group), linewidth = 0.4) +
  geom_path(data = sa_provinces, aes(group = group), linewidth = 0.2) +
  scale_fill_manual("Temp. (°C)", values = cols11) + # Set the colour palette
  coord_equal(xlim = c(15, 34), ylim = c(-36, -26), expand = 0)
```

```{r}
ggplot(data = rast_annual, aes(x = lon, y = lat)) +
  geom_tile(data = sst, aes(fill = bins)) +
  scale_fill_manual("Temp. (°C)", values = cols11) +
  geom_polygon(data = south_africa_coast,
               colour = "black", fill = "grey70",
               aes(group = group), linewidth = 0.4) +
  geom_path(data = sa_provinces, aes(group = group), linewidth = 0.2) +
  geom_tile(data = rast_annual, aes(x = lon, y = lat, fill = bins), 
            colour = "white", size = 0.1) + # The coastal temperature values
  coord_equal(xlim = c(15, 34), ylim = c(-36, -26), expand = 0)
```

```{r}
final_map <- ggplot(data = rast_annual, aes(x = lon, y = lat)) +
  geom_tile(aes(x = lon, y = lat, fill = bins), 
            colour = "white", size = 0.1) +
  geom_raster(data = sst, aes(fill = bins)) +
  geom_polygon(data = south_africa_coast,
               colour = "black", fill = "grey70",
               aes(group = group), linewidth = 0.4) +
  geom_path(data = sa_provinces, aes(group = group), linewidth = 0.2) +
  geom_tile(aes(x = lon, y = lat, fill = bins), 
            colour = "white", size = 0.1) +
  scale_fill_manual("Temp. (°C)", values = cols11) +
  coord_equal(xlim = c(15, 34), ylim = c(-36, -26), expand = 0) +
  scale_x_continuous(position = "top") + # Put x axis labels on top of figure
  theme(axis.title = element_blank(), # Remove the axis labels
        legend.text = element_text(size = 7), # Change text size in legend
        legend.title = element_text(size = 7), # Change legend title text size
        legend.key.height = unit(0.3, "cm"), # Change size of legend
        legend.background = element_rect(colour = "white"), # Add legend background
        legend.justification = c(1, 0), # Change position of legend
        legend.position = c(0.975, 0.05) # Fine tune position of legend
        )
final_map
```

```{r}
# Load libraries
# library(tidyverse)
library(scales)
# install.packages("ggspatial")
library(ggspatial)

# Load Africa map
load("data/SAMOS/other_data/africa_map.RData")
```


```{r}
sa_1 <- ggplot() +
  borders(col = "black", fill = "cornsilk", linewidth = 0.2) +
  geom_tile(data = sst, aes(x = lon, y = lat, fill = bins)) +
  scale_fill_manual("Temp. (°C)", values = cols11) +
  coord_equal(xlim = c(12, 36), ylim = c(-38, -22), expand = 0)
```


```{r}
sa_2 <- sa_1 +
  annotate(
    "text",
    label = "Atlantic\nOcean",
    x = 16.5,
    y = -34.0,
    size = 2.0,
    angle = 0,
    colour = "navy"
  ) +
  annotate(
    "text",
    label = "Indian\nOcean",
    x = 30.0,
    y = -34.0,
    size = 2.0,
    angle = 0,
    colour = "red4"
  )
sa_2
```


```{r}
# install.packages("rnaturalearth", "rnaturalearthdata", "sf")
library(tidyverse)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

# for the buffer to work as I expect, switch off
# the functions for spherical geometry:
sf_use_s2(FALSE)
```

```{r}
# the full map extent:
xmin <- 12; ymin <- -36.5; xmax <- 40.5; ymax <- -10
xlim <- c(xmin, xmax); ylim <- c(ymin, ymax)

# make a bounding box for cropping:
bbox <- st_bbox(c(xmin = xmin, ymin = ymin,
  xmax = xmax, ymax = ymax))

# might be useful for zooming into a smaller region (False Bay and 
# the Cape Peninsula):
xlim_zoom <- c(17.8, 19); ylim_zoom <- c(-34.5, -33.2)
```

```{r}
# load the countries:
safrica_countries <- ne_countries(returnclass = 'sf',
  continent = "Africa",
  country = c("South Africa", "Mozambique",
    "Namibia", "Zimbabwe", "Botswana",
    "Lesotho", "Eswatini"),
  scale = "medium")
```

```{r}
# Run this on your PC... the output is too voluminous for here
glimpse(safrica_countries)
st_crs(safrica_countries)
unique(safrica_countries$formal_en)
```

```{r}
safrica_countries |> 
  dplyr::filter(sovereignt == "South Africa") |> 
  select(sovereignt) |> 
  plot()
```

```{r}
safrica_countries_new <- safrica_countries |> 
  group_by(continent) |> 
  summarise() |> 
  st_crop(bbox) |>
  st_combine()

plot(safrica_countries_new)
```

```{r}
ggplot() +
  geom_sf(data = safrica_countries,
    colour = "indianred", fill = "beige") +
  coord_sf(xlim = xlim,
           ylim = ylim) +
  theme_bw()
  
```

```{r}
buffer <- safrica_countries_new %>%
  st_buffer(0.4)

ggplot() +
  geom_sf(data = buffer, fill = "lightblue", col = "transparent") +
  geom_sf(data = safrica_countries, colour = "indianred", fill = "beige") +
  theme_minimal()
```

